### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by erikd** [noteed/acme#2]
There is no indication whatsoever about what license (if any) this code is released under. In most legal jurisdictions, this defaults to "All Right Reserved" which means that no one can use it without your explicit permission. If your intention is to make this code as widely usable as possible, may I suggest a 2-clause BSD license like [this one](https://github.com/erikd/wide-word/blob/master/LICENSE). All you need to do is replace my name with yours.

**Comment by noteed** [comment]
Hey, sorry I don't know how I miss so many GH notifications. Anyway, I'll add a 2-clause BSD license. (Other repos of mine are usuallly 3-clause but I don't mind changing.)

**Comment by erikd** [comment]
I'd be happy with any of the BSD, or MIT or GNU licences. Totally up to you :).

**Comment by erikd** [comment]
:100: Thanks!
